// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJTPXuh21JPN4G3GS9OV705_WQk4wZ1Xw',
    appId: '1:238762077478:web:ad46f212618a84f19fe5e7',
    messagingSenderId: '238762077478',
    projectId: 'etkinlikapp-4fb16',
    authDomain: 'etkinlikapp-4fb16.firebaseapp.com',
    storageBucket: 'etkinlikapp-4fb16.appspot.com',
    measurementId: 'G-8K0R85RHJ7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrhu9akdu6FZXqPmQxScUoVXPGlEcf_RQ',
    appId: '1:238762077478:android:d92b916b6b55d1719fe5e7',
    messagingSenderId: '238762077478',
    projectId: 'etkinlikapp-4fb16',
    storageBucket: 'etkinlikapp-4fb16.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCAx8GwjwEIblR54jbljhqVjkTd86Tj2ks',
    appId: '1:238762077478:ios:114ffada5e837b769fe5e7',
    messagingSenderId: '238762077478',
    projectId: 'etkinlikapp-4fb16',
    storageBucket: 'etkinlikapp-4fb16.appspot.com',
    iosBundleId: 'com.example.etkinlikapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCAx8GwjwEIblR54jbljhqVjkTd86Tj2ks',
    appId: '1:238762077478:ios:55a8ad90c7b301129fe5e7',
    messagingSenderId: '238762077478',
    projectId: 'etkinlikapp-4fb16',
    storageBucket: 'etkinlikapp-4fb16.appspot.com',
    iosBundleId: 'com.example.etkinlikapp.RunnerTests',
  );
}
